## Template 
original_data: Task08_HepaticVessel  # Task03_Liver
DATASET_DIR: /data0/JY/project/algorithm/nnUNet/DATASET
output_identifier: pretrain #nnUNet
default_plans_identifier: "nnUNetPlansv2.1"
default_data_identifier: 'nnUNet'
default_trainer: "nnUNetTrainerV2"
default_cascade_trainer: "nnUNetTrainerV2CascadeFullRes"
nnUNet_def_n_proc: 8
train_module: dp  # single ,dp, ddp

preprocessing_args:
  task_ids: [8]
  pl3d: ExperimentPlanner3D_v21
  pl2d: ExperimentPlanner2D_v21
  no_pp: False
  tl: 8
  tf: 8
  verify_integrity: False

training_args:
  network: 3d_fullres
  task_id: 101
  fold: 5
  validation_only: False
  continue_training: False
  npz: False
  disable_saving: False

training_single:
  network_trainer: nnUNetTrainerV2
  
training_dp:
  gpus: 4
  dbs: False
  network_trainer: nnUNetTrainerV2_DP

training_ddp:
  gpus: 4
  dbs: False
  network_trainer: nnUNetTrainerV2_DDP

inference_args:
  input_folder: nnUNet_raw/nnUNet_raw_data/Task008_HepaticVessel/imagesTs
  output_folder: output
  task_id: 8
  model: 3d_fullres
  folds: [4] # [0, 1, 2, 3, 4]
  save_npz: False
  gpus: 4
  disable_mixed_precision: False
  

