# convert_decathlon:
#   original_data: Task101_Ovary   

# preprocessing_args:
#   task_ids: [101]
#   pl3d: ExperimentPlanner3D_v21
#   pl2d: ExperimentPlanner2D_v21
#   no_pp: False
#   verify_integrity: False

train_module: dp  # single ,dp, ddp

# training_args:
#   network: 3d_cascade_fullres  # 2d, 3d_fullres, 3d_lowres, 3d_cascade_fullres
#   task_id: 101
#   fold: 0
#   validation_only: False
#   continue_training: False
#   npz: False
#   disable_saving: False

# training_single:
#   network_trainer: nnUNetTrainerCascadeFullRes  #nnUNetTrainerV2_CascadeFullRes
#   using_pretrain: True
  
# training_dp:
#   gpus: 4
#   dbs: False
#   network_trainer: nnUNetTrainerCascadeFullRes

# training_ddp:
#   gpus: 4
#   dbs: False
#   network_trainer: nnUNetTrainerCascadeFullRes

inference_args:
  input_folder: nnUNet_raw/nnUNet_raw_data/Task101_Ovary/imagesTs
  output_folder: output
  task_id: 101
  model: 2d  # 2d, 3d_fullres, 3d_lowres, 3d_cascade_fullres
  folds: [0] # [0, 1, 2, 3, 4]
  save_npz: False #True
  gpus: 1
  mode: normal  # normal, fast, fastest   ! 2d need use normal mode
  disable_mixed_precision: False
  overwrite_existing: False   # set false, if exist: exit
  using_pretrain: True
  eval_flag: True
  default_trainer: nnUNetTrainerV2
  
  

