convert_decathlon:
  original_data: Task03_Liver   

preprocessing_args:
  task_ids: [3]
  pl3d: ExperimentPlanner3D_v21
  pl2d: ExperimentPlanner2D_v21
  no_pp: False
  verify_integrity: False

train_module: single  # single ,dp, ddp

training_args:
  network: 3d_fullres  # 2d, 3d_fullres, 3d_lowres, 3d_cascade_fullres
  task_id: 3
  fold: 4
  validation_only: True
  continue_training: False
  npz: False
  disable_saving: False

training_single:
  network_trainer: nnUNetTrainerV2
  using_pretrain: True
  
training_dp:
  gpus: 4
  dbs: False
  network_trainer: nnUNetTrainerV2_DP

training_ddp:
  gpus: 4
  dbs: False
  network_trainer: nnUNetTrainerV2_DDP

inference_args:
  input_folder: nnUNet_raw/nnUNet_raw_data/Task003_Liver/imagesTs
  output_folder: output
  task_id: 3
  model: 3d_fullres
  folds: [4] # [0, 1, 2, 3, 4]
  save_npz: True
  gpus: 1
  mode: normal  # normal, fast, fastest
  disable_mixed_precision: False
  overwrite_existing: False   # set false, if exist: exit
  using_pretrain: True
  

