################# THESE DO NOT NECESSARILY NEED TO BE MODIFIED #####################
patience : 50
val_eval_criterion_alpha : 0.9  # alpha * old + (1-alpha) * new
train_loss_MA_alpha : 0.93  # alpha * old + (1-alpha) * new
train_loss_MA_eps : 5e-4  # new MA must be at least this much better (smaller)

################# epoch set #####################
max_num_epochs : 250
num_batches_per_epoch : 250
num_val_batches_per_epoch : 50
also_val_in_tr_mode : False
lr_threshold : 1e-6  # the network will not terminate training if the lr is still above this threshold

################# LEAVE THESE ALONE ################################################
val_eval_criterion_MA : None
train_loss_MA : None
best_val_eval_criterion_MA : None
best_MA_tr_loss_for_patience : None
best_epoch_based_on_MA_tr_loss : None
all_tr_losses : []
all_val_losses : []
all_val_losses_tr_mode : []
all_val_eval_metrics : []  # does not have to be used
epoch : 0
log_file : None
deterministic : deterministic
use_progress_bar : False

################# Settings for saving checkpoints ##################################
save_every : 50
save_latest_only : True  # if false it will not store/overwrite _latest but separate files each
# time an intermediate checkpoint is created
save_intermediate_checkpoints : True  # whether or not to save checkpoint_latest
save_best_checkpoint : True  # whether or not to save the best checkpoint according to best_val_eval_criterion_MA
save_final_checkpoint : True  # whether or not to save the final checkpoint